name: ðŸ”¬ Deploy yDaemon develop
on:
  workflow_dispatch:
    inputs:
      docker_image_tag:
        description: Docker image tag
        required: true
        default: latest
  workflow_run:
    workflows: ["â˜ƒ Build & publish docker image"]
    types:
      - completed

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: extract docker image tag
        id: extract_tag
        run: |
          TAG=${{ github.event.inputs.docker_image_tag }}
          echo "value=${TAG:-latest}" >> $GITHUB_OUTPUT
      - name: Deploy to yDaemon dev
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.YD_DEV_HOST }}
          username: ${{ secrets.YD_DEV_USERNAME }}
          key: ${{ secrets.YD_DEV_KEY }}
          port: ${{ secrets.YD_DEV_PORT }}
          script: curl "https://raw.githubusercontent.com/mariuspod/ydaemon/develop/deploy.sh" -o deploy.sh && chmod +x deploy.sh && ./deploy.sh "${{ steps.extract_tag.outputs.value }}"
