name: Validation
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    name: Lint data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1

      - name: Lint data
        run: |
          npm install -g prettier
          prettier --check ./data/meta/**/*.json

  verify:
    name: Verify data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install deps (with cache)
        uses: bahmutov/npm-install@v1

      - name: Verify data
        run: node ./data/meta/_config/scripts/verify.mjs
